import pandas as pd
import re
import datetime

def _fmt_date(val):
    """Return SQL date expression or NULL for a pandas / python date-like value."""
    if pd.isna(val):
        return 'NULL'
    if not isinstance(val, (pd.Timestamp, datetime.date, datetime.datetime)):
        val = pd.to_datetime(val, errors='coerce')
    if pd.isna(val):
        return 'NULL'
    return f"TO_DATE('{val.strftime('%Y-%m-%d')}', 'YYYY-MM-DD')"

def clean_water_usage_data():
    # Load the Excel file into a DataFrame
    df = pd.read_excel("UTILITY USAGE.xlsx", sheet_name="WATER")

    # Forward fill the ACCOUNT column so missing values get filled from above
    df["ACCOUNT"] = df["ACCOUNT"].fillna(method="ffill")
    df["VENDOR"] = df["VENDOR"].fillna(method="ffill")
    df["SERVICE ADDRESS"] = df["SERVICE ADDRESS"].fillna(method="ffill")

    # Remove any rows where the METER_READ_DATE is missing or before MAY 1, 2025
    df = df[df["METER READ DATE "].notna() & (df["METER READ DATE "] >= pd.Timestamp("2025-05-01"))]
    
    accounts_df = pd.read_excel('usage_accounts.xlsx')

    # Convert account numbers to strings before merging
    df["ACCOUNT"] = df["ACCOUNT"].astype(str)
    accounts_df["ACCOUNT_NUMBER"] = accounts_df["ACCOUNT_NUMBER"].astype(str)
    
    # Replace vendor in df with the vendor from accounts based on the account number
    df = df.merge(accounts_df[['VENDOR', 'ACCOUNT_NUMBER']], left_on='ACCOUNT', right_on='ACCOUNT_NUMBER', how='left')
# create table rfi.intelex_util_usage_tbl (
#     util_usage_id                             number generated by default on null as identity 
#                                    constraint rfi_intelex_util_id_pk primary key,
#     util_usage_type                varchar2(255 char) not null, 
#     vendor                         varchar2(4000 char),
#     account_number                 number,
#     service_address                varchar2(4000 char),
#     read_date                      date,
#     previous_usage                 number,
#     present_usage                  number,
#     monthly_usage                  number,
#     total_usage                    number,
#     usage_uom_id                   number 
#         constraint rfi_intelex_util_usage_uom_fk 
#             references rfi.intelex_usage_uom_tbl(usage_uom_id),
#     dollar_amount                  number,
#     date_received                  date,
#     electrical_dollar_amount       number,
#     water_dollar_amount            number,
#     secruity_dollar_amount         number,
#     created                        date not null,
#     created_by                     varchar2(255 char) not null,
#     updated                        date not null,
#     updated_by                     varchar2(255 char) not null
# )
# ;
    # create insert statements for the cleaned data
    with open('water_insert_statements.sql', 'w') as f:
        for index, row in df.iterrows():
            insert_statement = f"""INSERT INTO rfi.intelex_util_usage_tbl (
                util_usage_type, vendor, account_number, service_address, read_date,
                previous_usage, present_usage, monthly_usage,
                usage_uom_id, dollar_amount, date_received, created, created_by,
                updated, updated_by
            ) VALUES (
                'WATER', '{row['VENDOR_y']}', {row['ACCOUNT_NUMBER']}, '{row['SERVICE ADDRESS']}',
                TO_DATE('{row['METER READ DATE '].strftime('%Y-%m-%d')}', 'YYYY-MM-DD'),
                {row['PREVIOUS USAGE']}, {row['PRESENT USAGE']}, {row['MONTHLY USAGE ']}
                , 11, {row['DOLLAR AMOUNT']}, to_date('{row['DATE RECEIVED'].strftime('%Y-%m-%d')}', 'YYYY-MM-DD'),
                SYSDATE, 'SCRIPT', SYSDATE, 'SCRIPT'
            );\n"""
            f.write(insert_statement)


    # Save the cleaned DataFrame to a new Excel file
    df.to_excel("cleaned_water_data.xlsx", index=False)

    print("Finished WATER")

def clean_gas_usage_data():
    # Load the Excel file into a DataFrame
    df = pd.read_excel("UTILITY USAGE.xlsx", sheet_name="GAS")

    df = df.rename(columns={"ACCOUNT NUMBER ": "ACCOUNT_NUMBER_ORIG"})

    # Forward fill the ACCOUNT column so missing values get filled from above
    df["ACCOUNT_NUMBER_ORIG"] = df["ACCOUNT_NUMBER_ORIG"].fillna(method="ffill")
    df["VENDOR "] = df["VENDOR "].fillna(method="ffill")

    # Remove any rows where the METER_READ_DATE is missing or before MAY 1, 2025
    df = df[df["READ DATE"].notna() & (df["READ DATE"] >= pd.Timestamp("2025-05-01"))]

    accounts_df = pd.read_excel('usage_accounts.xlsx')

    # Convert account numbers to strings before merging
    df["ACCOUNT_NUMBER_ORIG"] = df["ACCOUNT_NUMBER_ORIG"].astype(str).str.replace('.0', '', regex=False)
    accounts_df["ACCOUNT_NUMBER"] = accounts_df["ACCOUNT_NUMBER"].astype(str).str.strip()
    
    # Replace vendor in df with the vendor from accounts based on the account number
    df = df.merge(accounts_df[['VENDOR', 'ACCOUNT_NUMBER']], left_on='ACCOUNT_NUMBER_ORIG', right_on='ACCOUNT_NUMBER', how='left')


    # create table rfi.intelex_util_usage_tbl (
    #     util_usage_id                             number generated by default on null as identity 
    #                                    constraint rfi_intelex_util_id_pk primary key,
    #     util_usage_type                varchar2(255 char) not null, 
    #     vendor                         varchar2(4000 char),
    #     account_number                 number,
    #     service_address                varchar2(4000 char),
    #     read_date                      date,
    #     previous_usage                 number,
    #     present_usage                  number,
    #     monthly_usage                  number,
    #     total_usage                    number,
    #     usage_uom_id                   number 
    #         constraint rfi_intelex_util_usage_uom_fk 
    #             references rfi.intelex_usage_uom_tbl(usage_uom_id),
    #     dollar_amount                  number,
    #     date_received                  date,
    #     electrical_dollar_amount       number,
    #     water_dollar_amount            number,
    #     secruity_dollar_amount         number,
    #     created                        date not null,
    #     created_by                     varchar2(255 char) not null,
    #     updated                        date not null,
    #     updated_by                     varchar2(255 char) not null
    # )
    # ;
    # create insert statements for the cleaned data
    with open('gas_insert_statements.sql', 'w') as f:
        for index, row in df.iterrows():
            date_received_sql = _fmt_date(row['DATE RECEIVED'])
            insert_statement = f"""INSERT INTO rfi.intelex_util_usage_tbl (
                util_usage_type, vendor, account_number, service_address, read_date,
                previous_usage, present_usage, monthly_usage,
                usage_uom_id, dollar_amount, date_received, created, created_by,
                updated, updated_by
            ) VALUES (
                'GAS', '{row['VENDOR']}', {row['ACCOUNT_NUMBER_ORIG']}, null,
                TO_DATE('{row['READ DATE'].strftime('%Y-%m-%d')}', 'YYYY-MM-DD'),
                {row['PREVIOUS USAGE']}, {row['PRESENT USAGE']}, {row['MONTHLY USAGE']}
                , null, {row['DOLLAR AMOUNT ']}, {date_received_sql},
                SYSDATE, 'SCRIPT', SYSDATE, 'SCRIPT'
            );\n"""
            f.write(insert_statement)

    # Save the cleaned DataFrame to a new Excel file
    df.to_excel("cleaned_gas_data.xlsx", index=False)

    print("Finished GAS")

def clean_electric_usage_data():
    # Load the Excel file into a DataFrame
    df = pd.read_excel("UTILITY USAGE.xlsx", sheet_name="ELECTRICITY")
    
    df = df.rename(columns={"ACCOUNT NUMBER": "ACCOUNT_NUMBER_ORIG"})
    # Forward fill the ACCOUNT column so missing values get filled from above
    df["ACCOUNT_NUMBER_ORIG"] = df["ACCOUNT_NUMBER_ORIG"].fillna(method="ffill")
    df["VENDOR "] = df["VENDOR "].fillna(method="ffill")

    # Convert the READ DATE column to datetime
    df["READ DATE"] = pd.to_datetime(df["READ DATE"], errors='coerce')
    
    # Remove any rows where the METER_READ_DATE is missing or before MAY 1, 2025
    df = df[df["READ DATE"].notna() & (df["READ DATE"] >= pd.Timestamp("2025-05-01"))]

    accounts_df = pd.read_excel('usage_accounts.xlsx')
    # Convert account numbers to strings before merging
    df["ACCOUNT_NUMBER_ORIG"] = df["ACCOUNT_NUMBER_ORIG"].astype(str).str.strip()
    accounts_df["ACCOUNT_NUMBER"] = accounts_df["ACCOUNT_NUMBER"].astype(str).str.strip()
    
    # Replace vendor in df with the vendor from accounts based on the account number
    df = df.merge(accounts_df[['VENDOR', 'ACCOUNT_NUMBER']], left_on='ACCOUNT_NUMBER_ORIG', right_on='ACCOUNT_NUMBER', how='left')

    # create table rfi.intelex_util_usage_tbl (
    #     util_usage_id                             number generated by default on null as identity
    #                                    constraint rfi_intelex_util_id_pk primary key,
    #     util_usage_type                varchar2(255 char) not null,
    #     vendor                         varchar2(4000 char),
    #     account_number                 number,
    #     service_address                varchar2(4000 char),
    #     read_date                      date,
    #     previous_usage                 number,
    #     present_usage                  number,
    #     monthly_usage                  number,
    #     total_usage                    number,
    #     usage_uom_id                   number
    #         constraint rfi_intelex_util_usage_uom_fk
    #             references rfi.intelex_usage_uom_tbl(usage_uom_id),
    #     dollar_amount                  number,
    #     date_received                  date,
    #     electrical_dollar_amount       number,
    #     water_dollar_amount            number,
    #     secruity_dollar_amount         number,
    #     created                        date not null,
    #     created_by                     varchar2(255 char) not null,
    #     updated                        date not null,
    #     updated_by                     varchar2(255 char) not null
    # )
    # ;
    # create insert statements for the cleaned data
    with open('electric_insert_statements.sql', 'w') as f:
        for index, row in df.iterrows():
            date_received_sql = _fmt_date(row['DATE RECEIVED'])
            insert_statement = f"""INSERT INTO rfi.intelex_util_usage_tbl (
                util_usage_type, vendor, account_number, service_address, read_date,
                previous_usage, present_usage, total_usage,
                usage_uom_id, dollar_amount, date_received, created, created_by,
                updated, updated_by
            ) VALUES (
                'ELECTRIC', '{row['VENDOR']}', {row['ACCOUNT_NUMBER_ORIG']}, null,
                TO_DATE('{row['READ DATE'].strftime('%Y-%m-%d')}', 'YYYY-MM-DD'),
                {row['PREVIOUS USAGE']}, {row['PRESENT USAGE']}, {row['TOTAL USAGE']}
                , null, {row['DOLLAR AMOUNT ']}, {date_received_sql},
                SYSDATE, 'SCRIPT', SYSDATE, 'SCRIPT'
            );\n"""
            f.write(insert_statement)
    # Save the cleaned DataFrame to a new Excel file
    df.to_excel("cleaned_electric_data.xlsx", index=False)

    print("Finished ELECTRIC")

def clean_summit_data():
    # Load the Excel file into a DataFrame, only the 2025 sheet, without headers
    df = pd.read_excel('SUMMIT USAGE.xlsx', sheet_name='2025', header=None)

    # Define months and their corresponding row indices for usage and dollar amounts
    months = ['MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']
    usage_rows = {month: idx for idx, month in enumerate(months, start=6)}   # Block 1: rows 6-13 (usage)
    dollar_rows = {month: idx for idx, month in enumerate(months, start=24)}  # Block 2: rows 24-31 (dollar)

    # Define corresponding first-of-month dates for 2025
    date_map_2025 = {month: pd.Timestamp(f'2025-{i+5}-01') for i, month in enumerate(months)}

    # Initialize lists to store transformed data
    transformed_data = []

    # Get meter numbers from the first row, starting from the second column (index 1)
    meter_numbers = df.iloc[0, 1:].dropna().tolist()

    # Normalize first column for matching
    df.iloc[:, 0] = df.iloc[:, 0].astype(str).str.strip().str.upper()

    # Debug: Print unique values in the first column
    print("Unique row labels in first column:", df.iloc[:, 0].unique())

    # Debug: Print sample rows around usage and dollar indices
    print("\nSample rows (5-15):")
    print(df.iloc[5:16, :5])  # First 5 columns for brevity
    print("\nSample rows (23-33):")
    print(df.iloc[23:34, :5])

    # Function to attempt converting a value to float, handling text
    def safe_float(value, is_dollar=False):
        if pd.isna(value):
            return None
        try:
            # If value is a string
            if isinstance(value, str):
                # For usage, only accept purely numeric strings (e.g., '6', '-72.27')
                if not is_dollar:
                    if not re.match(r'^-?\d*\.?\d+$', value.strip()):
                        return None
                # For dollar amounts, extract numeric portion (e.g., 'NEW ACCT NUMBER 2855.01' -> 2855.01)
                match = re.search(r'-?\d+\.?\d*', value)
                if match:
                    return float(match.group())
                return None
            return float(value)
        except (ValueError, TypeError):
            return None

    # Process 2025 data
    for meter in meter_numbers:
        print(f"\nProcessing meter: {meter}")
        meter_col_idx = df.iloc[0][df.iloc[0] == meter].index[0]  # Find column index for this meter
        for month in months:
            # Get usage from block 1 (rows 6-13)
            usage_row = usage_rows[month]  # e.g., MAY at row 6
            usage = df.loc[usage_row, meter_col_idx] if usage_row in df.index else None
            
            # Get dollar amount from block 2 (rows 24-31)
            dollar_row = dollar_rows[month]  # e.g., MAY at row 24
            dollar = df.loc[dollar_row, meter_col_idx] if dollar_row in df.index else None

            # Only add row if usage is a valid number
            usage_value = safe_float(usage, is_dollar=False)
            if usage_value is not None:
                dollar_value = safe_float(dollar, is_dollar=True)
                row_data = {
                    'ACCOUNT_NUMBER': str(meter),
                    'DATE': date_map_2025[month],
                    'USAGE_AMOUNT': usage_value,
                    'DOLLAR_AMOUNT': dollar_value
                }
                transformed_data.append(row_data)
                print(f"Added data for {month}, meter {meter}: usage={usage} (row {usage_row}), dollar={dollar} (row {dollar_row})")

    # Create DataFrame from transformed data
    result_df = pd.DataFrame(transformed_data)

    # get accounts data
    accounts_df = pd.read_excel('summit_accounts.xlsx')

    # Convert account numbers to strings before merging
    # alse remove any thing to the right of '/' in account numbers if it exists
    result_df["ACCOUNT_NUMBER"] = (
        result_df["ACCOUNT_NUMBER"]
        .astype(str)
        .str.strip()
        .str.replace(r'/.*', '', regex=True)   # remove "/" and everything after
    )
    accounts_df["METER_NUMBER"] = accounts_df["METER_NUMBER"].astype(str).str.strip()

    print(result_df.head())
    print(accounts_df.head())

    # merge with accounts_df to get location information
    result_df = result_df.merge(accounts_df[['LOCATION', 'METER_NUMBER']], left_on='ACCOUNT_NUMBER', right_on='METER_NUMBER', how='left')

#     create table rfi.intelex_summit_usage_tbl (
#     summit_usage_id                             number generated by default on null as identity 
#                                    constraint rfi_intelex_summit_id_pk primary key,
#     location                       varchar2(255 char),
#     meter_number                   varchar2(255 char),
#     read_date                      date,
#     usage_amount                   number,
#     dollar_amount                  number,
#     created                        date not null,
#     created_by                     varchar2(255 char) not null,
#     updated                        date not null,
#     updated_by                     varchar2(255 char) not null
# )
    with open('summit_insert_statements.sql', 'w') as f:
        for index, row in result_df.iterrows():
            insert_statement = f"""INSERT INTO rfi.intelex_summit_usage_tbl (
                location, meter_number, read_date, usage_amount, dollar_amount, created, created_by, updated, updated_by
            ) VALUES (
                '{row['LOCATION']}', '{row['ACCOUNT_NUMBER']}', TO_DATE('{row['DATE']}', 'YYYY-MM-DD'),
                {row['USAGE_AMOUNT']}, {row['DOLLAR_AMOUNT'] if pd.notna(row['DOLLAR_AMOUNT']) else 'NULL'},
                SYSDATE, 'SCRIPT', SYSDATE, 'SCRIPT'
            );\n"""
            f.write(insert_statement)
    # Save to a new Excel file
    result_df.to_excel('cleaned_summit_data.xlsx', index=False)

    print("Finished SUMMIT")

def clean_energy_data():
    # Load the 2025 sheet from energy_usage.xlsx without headers
    df = pd.read_excel('energy_usage.xlsx', sheet_name='2025', header=None)

    # Define months and their corresponding row indices for usage and dollar amounts
    months = ['MAY','JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC']
    usage_rows = {month: idx for idx, month in enumerate(months, start=7)}   # Block 1: rows 6-13 (usage)
    second_rows = {month: idx for idx, month in enumerate(months, start=20)}  # Block 2: rows 24-31 (dollar)
    dollar_rows = {month: idx for idx, month in enumerate(months, start=33)}  # Block 3: rows 24-31 (dollar)

    # Initialize lists to store transformed data
    transformed_data = []

    # Get meter numbers from the first row, starting from the second column (index 1)
    meter_numbers = df.iloc[1, 1:].dropna().tolist()


    # Process 2025 data
    for meter in meter_numbers:
        # print(f"\nProcessing meter: {meter}")
        meter_col_idx = df.iloc[1][df.iloc[1] == meter].index[0]  # Find column index for this meter
        # print(f"Meter column index: {meter_col_idx}")
        for month in months:
            # Get usage from block 1 (rows 6-13)
            usage_row = usage_rows[month]  # e.g., MAY at row 6
            prev_date = df.loc[usage_row - 1, meter_col_idx] if (usage_row - 1) in df.index else None
            usage_date = df.loc[usage_row, meter_col_idx] if usage_row in df.index else None
            usage = df.loc[usage_row, meter_col_idx + 1] if usage_row in df.index else None
            # print(f"usage_date: {usage_date}")
            
            # Get usage from block 1 (rows 6-13)
            second_row = second_rows[month]  # e.g., MAY at row 6
            kw = df.loc[second_row, meter_col_idx] if second_row in df.index else None
            kva = df.loc[second_row, meter_col_idx + 1] if second_row in df.index else None
            
            # Get dollar amount from block 2 (rows 24-31)
            dollar_row = dollar_rows[month]  # e.g., MAY at row 24
            days_between = df.loc[dollar_row, meter_col_idx] if dollar_row in df.index else None
            dollar = df.loc[dollar_row, meter_col_idx + 1] if dollar_row in df.index else None

            # Only add row if usage is a valid number
            # usage_value = safe_float(usage, is_dollar=False)
            if pd.notna(usage_date):
                row_data = {
                    'ACCOUNT_NUMBER': str(meter),
                    'PREV_DATE': prev_date,
                    'DATE': usage_date,
                    'USAGE_KWH': usage,
                    'USAGE_KW': kw,
                    'USAGE_KVA': kva,
                    'DAYS_BETWEEN': days_between,
                    'DOLLAR_AMOUNT': dollar
                }
                transformed_data.append(row_data)
                # print(f"Added data for {month}, meter {meter}")

    # # Create DataFrame from transformed data
    result_df = pd.DataFrame(transformed_data)

    accounts_df = pd.read_excel('energy_accounts.xlsx')

    # Convert account numbers to strings before merging
    result_df["ACCOUNT_NUMBER"] = result_df["ACCOUNT_NUMBER"].astype(str).str.strip()
    accounts_df["ACCOUNT_NUMBER"] = accounts_df["ACCOUNT_NUMBER"].astype(str).str.replace('.0', '', regex=False)

    print(result_df.head())
    print(accounts_df.head())
    # merge with accounts_df to get location information
    result_df = result_df.merge(accounts_df[['LOCATION', 'ACCOUNT_NUMBER']], on='ACCOUNT_NUMBER', how='left')

    # # Save to a new Excel file
    result_df.to_excel('cleaned_energy_data.xlsx', index=False)

    ## create oracle insert statements

#     create table rfi.intelex_energy_usage_tbl (
#     energy_usage_id                             number generated by default on null as identity 
#                                    constraint rfi_intelex_energy_id_pk primary key,
#     location                       varchar2(255 char),
#     account_number                 number,
#     previous_read_date             date,
#     read_date                      date,
#     usage_kwh                      number,
#     usage_kw                       number,
#     usage_kva                      number,
#     days_between                   number,
#     dollar_amount                  number,
#     created                        date not null,
#     created_by                     varchar2(255 char) not null,
#     updated                        date not null,
#     updated_by                     varchar2(255 char) not null
# )
# ;
    with open('energy_insert_statements.sql', 'w') as f:
        for index, row in result_df.iterrows():
            insert_statement = f"""INSERT INTO rfi.intelex_energy_usage_tbl (
                location, account_number, previous_read_date, read_date, usage_kwh, usage_kw, usage_kva, days_between, dollar_amount, created, created_by, updated, updated_by
            ) VALUES (
                '{row['LOCATION']}', {row['ACCOUNT_NUMBER']}, TO_DATE('{row['PREV_DATE']}', 'YYYY-MM-DD'), TO_DATE('{row['DATE']}', 'YYYY-MM-DD'),
                {row['USAGE_KWH']}, {row['USAGE_KW']}, {row['USAGE_KVA']}, {row['DAYS_BETWEEN']}, {row['DOLLAR_AMOUNT']},
                SYSDATE, 'SCRIPT', SYSDATE, 'SCRIPT'
            );\n"""
            f.write(insert_statement)
    print("Energy insert statements created in 'energy_insert_statements.sql'")


    print("Finished ENERGY")

if __name__ == "__main__":
    # clean_water_usage_data()
    # clean_gas_usage_data()
    # clean_summit_data()
    # clean_energy_data()
    clean_electric_usage_data()
    print("All utility data cleaned successfully.")